import math

KP = 0.35
CP = 0.34

# Radians
SAIL_CONTROLLER_MAX_SAIL_ANGLE = math.pi / 2
APPARENT_WIND_ANGLE_TO_CLOSE_SAIL_RAD = 0.1
MIN_HEADING_ERROR_FOR_SWITCH = 0.1

# Knots
SPEED_THRSHOLD_FOR_JIBING_KNOTS = 0.5

# Seconds
SWITCH_INTERVAL = 5
MAX_TIME_FOR_TACKING = 10
MAX_TIME_FOR_JIBING = 10
