import math

# Adjust the nonlinear feedback Function
#
KP = 0.35
CP = 0.34

# 0 < X1 and X2 < PI
# X1 < X2
X1_SAIL = 0
X2_SAIL = math.pi

X1_JIB = 0
X2_JIB = math.pi

TIMESTAMP_UNAVAILABLE = -1

MAX_WINCH_POSITION = 360
MIN_WINCH_POSITION = 0

# Radians
SAIL_CONTROLLER_MAX_SAIL_ANGLE = math.pi / 2
JIB_CONTROLLER_MAX_SAIL_ANGLE = math.pi / 2
APPARENT_WIND_ANGLE_TO_CLOSE_SAIL_RAD = 0.1
MIN_HEADING_ERROR_FOR_SWITCH = 0.1
MAX_ABS_RUDDER_ANGLE_RAD = math.pi / 3
MAX_ABS_SAIL_ANGLE_RAD = math.pi / 2
MAX_ABS_JIB_ANGLE_RAD = math.pi / 2

# Knots
SPEED_THRESHOLD_FOR_JIBING_KNOTS = 0.5

# Seconds
SWITCH_INTERVAL = 5
MAX_TIME_FOR_TACKING = 10
MAX_TIME_FOR_JIBING = 10

# Degrees
MAX_ABS_RUDDER_ANGLE_DEG = 45
MAX_ABS_SAIL_ANGLE_DEG = 90
MAX_ABS_JIB_ANGLE_DEG = 90
